apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: app
build:
  artifacts:
  - image: jamilomar/test
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-app.yaml
